# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wq1DX2a_Dig_STtr3Zk03a5G8waUODs8
"""

from flask import Flask, request, jsonify
import joblib
import pandas as pd

app = Flask(__name__)
model = joblib.load("model.pkl")

@app.route('/')
def home():
    return "Accident Severity Prediction API is Running!"

@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Expect JSON with features as a dictionary
        data = request.get_json()
        input_df = pd.DataFrame([data])
        prediction = model.predict(input_df)
        return jsonify({'prediction': int(prediction[0])})
    except Exception as e:
        return jsonify({'error': str(e)})

if __name__ == '__main__':
    app.run(debug=True)